DROP TABLE IF EXISTS project_worker;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS worker;

CREATE TABLE worker (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) BETWEEN 2 AND 1000), -- гарантує верхню межу 1000 символів замість >=2
    BIRTHDAY DATE NOT NULL CHECK (BIRTHDAY > '1900-01-01'),
    LEVEL VARCHAR(10) NOT NULL CHECK (LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior')),
    SALARY INTEGER NOT NULL CHECK (SALARY >= 100 AND SALARY <= 100000)
);

CREATE TABLE client (
    ID  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) >= 2)
);

CREATE TABLE project (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENT_ID INTEGER NOT NULL REFERENCES client(ID),
    START_DATE DATE NOT NULL,
    FINISH_DATE DATE NOT NULL
);

CREATE TABLE project_worker (
    PROJECT_ID INTEGER NOT NULL REFERENCES project(ID),
    WORKER_ID INTEGER NOT NULL REFERENCES worker(ID),
    PRIMARY KEY (PROJECT_ID, WORKER_ID)
);


