SELECT
    'YOUNGEST' AS TYPE,
    NAME,
    BIRTHDAY
FROM Worker
WHERE BIRTHDAY = (
    SELECT MAX(BIRTHDAY) FROM Worker
    )
UNION ALL
SELECT
    'OLDEST' AS TYPE,
    NAME,
    BIRTHDAY
FROM Worker
WHERE BIRTHDAY = (
    SELECT MIN(BIRTHDAY) FROM Worker
    )
ORDER BY TYPE, BIRTHDAY;